name: Continuous Deployment Android

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  FILENAME: Squads

jobs:
  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 & Restore Gradle Cache
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: gradle
    
      # Permissions
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # Sign Release APK
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
       
        # Rename Signed APK
      - name: Rename Release APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} ${{ env.FILENAME }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}.apk
          path: ${{ env.FILENAME }}.apk

  release_apk:
    name: Release APK
    needs: [build_release_apk]
    runs-on: ubuntu-latest
    steps:
      # Download Signed APK
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.FILENAME }}.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v0.${{ github.run_number }}
          release_name: Release v0.${{ github.run_number }}

      - name: Upload Signed APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FILENAME }}.apk
          asset_name: ${{ env.FILENAME }}.apk
          asset_content_type: application/zip