name: Continuous Integration Android 

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 11

jobs:
  unit_tests:
    name: Testing
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2      

      # Set up JDK 11 & Restore Gradle Cache
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: gradle
      
      # Run Unit Tests
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Unit Tests
        run: ./gradlew test  --continue

      # Build Project
      - name: Build Project
        run: ./gradlew assemble

      # Upload Test Reports
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports/tests/

  linter:
    name: Linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 11 & Restore Gradle Cache
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: gradle

      # Run Debug Linter
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Debug Linter
        run: ./gradlew lintDebug

      # Upload Linter Report
      - name: Upload Linter Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: linter-report
          path: app/build/reports/lint-results-*

  build_debug_apk:
    name: Building Debug APK
#     needs: [emulator_test]
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 11 & Restore Gradle Cache
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: gradle

      # Build Debug APK
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/**.apk
