name: Build and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2  

      # Set up JDK 11 & Restore Gradle Cache
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: gradle
    
     - name: Set execution flag for gradlew
       run: chmod +x gradlew
       #BUILD APK

     - name: Build APK
       run: bash ./gradlew assembleDebug --stacktrace

       # Sign Release APK
     - name: Sign APK
       uses: r0adkll/sign-android-release@v1
      # ID used to access action output
       id: sign_app
       with:
         releaseDirectory: app/build/outputs/apk/release
         signingKeyBase64: ${{ secrets.SIGNING_KEY }}
         alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

        #Upload APK
     - name: Upload APK
       uses: actions/upload-artifact@v1
       with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk